version: "3"
services:
  redis:
    image: redis:alpine
    restart: unless-stopped
    ports:
      - "7001:6379"
  lobby:
    image: deploy_lobby:latest
    environment:
    - DEBUG=info:*,error:*
    - NAME=lobby
    - PORT=3007
    - RBMQ_PLATFORM_HOST=
    - RBMQ_PLATFORM_EXCHANGE=
    - RBMQ_PLATFORM_QUEUE=
    - RBMQ_PLATFORM_ROUTER=
    - CAS_API_HOST=
    - MONGO_URI=
    - REDIS_URL=
    - MYSQL_HOST=
    - MYSQL_PORT=
    - MYSQL_USERNAME=
    - MYSQL_PASSWORD=
    - MYSQL_DBNAME=
    ports:
    - "3007:3007"