version: "3"
services:
  redis:
    container_name: ace_dev_redis
    image: redis:alpine
    restart: unless-stopped
    expose:
    - "6379"
  lobby:
    build:
      context: ./
      dockerfile: ./lobby.dockerfile
    links:
    - redis
    restart: unless-stopped
    environment:
    - DEBUG=info:*,error:*
    - NAME=lobby
    - PORT=3007
    - RBMQ_PLATFORM_HOST=amqp://host.docker.internal:5672/service
    - RBMQ_PLATFORM_EXCHANGE=service_exchange
    - RBMQ_PLATFORM_QUEUE=service_queue
    - RBMQ_PLATFORM_ROUTER=service
    - CAS_API_HOST=http://host.docker.internal:8080/
    - MONGO_URI=mongodb://host.docker.internal:27017/db_service
    - REDIS_URL=redis://redis:6379/
    - MYSQL_HOST=host.docker.internal
    - MYSQL_PORT=3306
    - MYSQL_USERNAME=
    - MYSQL_PASSWORD=
    - MYSQL_DBNAME=
    ports:
    - "3007:3007"
networks:
  default:
    external:
      name: ace_bridge
