export enum SGStatusCode {
    SUCCESS = 0,
    FAIL = 1,
    //1xxxx AUTH
    USER_NAME_OR_PASSWORD_INVALID = 10000,
    USER_NAME_INVALID_FORMAT = 10001,
    USER_NAME_OR_EMAIL_EXISTS = 10003,
    EMAIL_INVALID_FORMAT = 10004,
    PASSWORD_CONFIMRED_NOT_CORRECT = 10005,
    PASSWORD_INVALID_FORMAT = 10006,
}

export enum SGCloseCode {
    KICK = 1001,
    BAN = 1002,
    OTHER = 1003
}

const SGStatusMessage: Map<SGStatusCode, string> = new Map([
    [SGStatusCode.SUCCESS, 'SUCCESS'],
    [SGStatusCode.FAIL, 'FAIL'],
    //1xxxx AUTH
    [SGStatusCode.USER_NAME_OR_PASSWORD_INVALID, 'USER_NAME_OR_PASSWORD_INVALID'],
    [SGStatusCode.USER_NAME_INVALID_FORMAT, 'USER_NAME_INVALID_FORMAT'],
    [SGStatusCode.USER_NAME_OR_EMAIL_EXISTS, 'USER_NAME_OR_EMAIL_EXISTS'],
    [SGStatusCode.PASSWORD_CONFIMRED_NOT_CORRECT, 'PASSWORD_CONFIMRED_NOT_CORRECT'],
    [SGStatusCode.PASSWORD_INVALID_FORMAT, 'PASSWORD_INVALID_FORMAT'],
    //2xxxx PAYMENT
]);
export default SGStatusMessage;
